### ISSUE TITLE
运行出错，求助。谢谢。

### ISSUE THREAD

**Issue by shenyinquan** [PChief/GushiwenSpider#2]
你好，我初次接触python,环境都是刚搭好，用户的Python3.5
在我运行view_spider 遇到如下错误，其他的author_spider  fanyi_spider 都正常，麻烦能帮忙看看嘛。 万分感谢。
`2016-11-04 13:59:35 [scrapy] INFO: Spider opened
2016-11-04 13:59:35 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-11-04 13:59:35 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6025
2016-11-04 13:59:50 [scrapy] ERROR: Error caught on signal handler: <bound method RedisMixin.spider_idle of <ViewSdier 'view_spider' at 0x40a4370>>
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\scrapy\utils\signal.py", line 30, in send_catch_log
    *arguments, **named)
  File "D:\Python\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "D:\Python\lib\site-packages\scrapy_redis\spiders.py", line 109, in spider_idle
    self.schedule_next_requests()
  File "D:\Python\lib\site-packages\scrapy_redis\spiders.py", line 103, in schedule_next_requests
    for req in self.next_requests():
  File "D:\Python\lib\site-packages\scrapy_redis\spiders.py", line 84, in next_requests
    req = self.make_request_from_data(data)
  File "D:\Python\lib\site-packages\scrapy_redis\spiders.py", line 96, in make_request_from_data
    if '://' in data:
TypeError: a bytes-like object is required, not 'str'
2016-11-04 13:59:50 [scrapy] INFO: Closing spider (finished)
2016-11-04 13:59:50 [scrapy] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 11, 4, 5, 59, 50, 461590),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 8,
 'start_time': datetime.datetime(2016, 11, 4, 5, 59, 35, 450253)}
2016-11-04 13:59:50 [scrapy] INFO: Spider closed (finished)`

**Comment by PChief** [comment]
你好，我看了下报错信息，通过源码可以判断是在view_spider从redis队列中读取url 的时候出的错。
**排查思路：**
    view_spider从view:start_urls中读取url，你在运行gushiwen后先别运行view_spider查看下redis队列中view:start_urls的值，看是否正常，在redis-cli下执行 sort view:start_urls
  如果不正常的话顺着代码可以找到文件
      gushiwen_spider.py的第37行itemld.add_xpath('view_urls', '//div[@class="typeleft"]/div[@class="sons"]/p[1]/a/@href')。
    通过scrapy shell调试下，确认是不是xpath 的问题。
**规避措施**，建议使用python2.7 + scrapy1.0.5。这是我的运行环境，你用的是python3.5，scrapy可能是1.2.0。排查兼容性问题比较困难。
以上供参考，欢迎随时交流
